CREATE TABLE biz_a (
    CGG_CODE NUMBER(38),
    SNT_COB_CODE NUMBER(38),
    YY NUMBER(38),
    UPSO_SNO VARCHAR2(26),
    SNT_COB_NM NVARCHAR2(456),
    PERM_NT_YMD DATE,
    UPSO_NM NVARCHAR2(456),
    SITE_ADDR_RD NVARCHAR2(456),
    SITE_ADDR NVARCHAR2(456),
    UPSO_SITE_TELNO VARCHAR2(300),
    BUP_NM NVARCHAR2(456),
    SITE_STDT date,
    ADMDNG_NM NVARCHAR2(300),
    DCB_YMD  DATE,
    DCB_GBN_NM NVARCHAR2(300),
    DCB_WHY NVARCHAR2(456),
    SNT_UPTAE_NM NVARCHAR2(456),
    GE_EH_YN NVARCHAR2(300),
    SITE_LOC_GBN NVARCHAR2(300),
    TRDP_AREA_ETC FLOAT,
    PERM_NT_NO VARCHAR2(456)
);

drop table biz_a;
